### ISSUE TITLE
PCB populating reference clarification

### ISSUE THREAD

**Issue by jparshook** [spenceraxani/CosmicWatch-Desktop-Muon-Detector#15]
On the PCB populating reference sheet, C14 is listed as a resistor (0 Ohm jumper) but is shown as a capacitor on the schematic. Could you please clarify the correct part for C14?

**Comment by spenceraxani** [comment]
Hi,

C14 can just be shorted with a 0Ohm resistor or a wire. 

Thanks,

Spencer
